### ISSUE TITLE
弱引用表述不严谨

### ISSUE THREAD

**Issue by liqiang1304** [doocs/jvm#3]
> 弱引用的**强度比软引用更弱**一些。当 JVM 进行垃圾回收时，**无论内存是否充足，都会回收**被软引用关联的对象。

应为：“都会回收**只被弱引用**关联的对象。”

**Comment by yanglbme** [comment]
@liqiang1304 你好，你的言外之意是，对象可能被弱引用和其它引用同时关联？

**Comment by liqiang1304** [comment]
> @liqiang1304 你好，你的言外之意是，对象可能被弱引用和其它引用同时关联？

原书的说法是：“当垃圾收集器工作时，无论当前内存是否足够，都会回收掉**只**被弱引用关联的对象”
我的理解是，当一个对象的所有强引用都断开，只剩弱引用时，他就有可能被GC

**Comment by yanglbme** [comment]
@liqiang1304 谢谢反馈，现在改过来。
