### ISSUE TITLE
标记清除算法表述错误

### ISSUE THREAD

**Issue by xxyxpy** [doocs/jvm#5]
标记的是存活对象，而不是需要清除的对象。
清除的是没有被标记的

**Comment by xxyxpy** [comment]
标记整理的描述貌似也有这样的问题

**Comment by yanglbme** [comment]
@xxyxpy 好的，谢谢反馈。你有相关资料提供吗？不妨把链接 or 图片贴出来？

**Comment by xxyxpy** [comment]
没找到标记清除算法对应的论文，只找到了维基百科中的说明和图片。
https://en.wikipedia.org/wiki/Tracing_garbage_collection#Na.C3.AFve_mark_and_sweep

![image](https://user-images.githubusercontent.com/25786642/59890845-657dc780-9405-11e9-988e-4ec628f4dbd6.png)

![image](https://user-images.githubusercontent.com/25786642/59890792-22235900-9405-11e9-97d5-b5c457a79d79.png)

**Comment by yanglbme** [comment]
@xxyxpy 好的，谢谢，目前已经改过来，有其它问题欢迎 issues 反馈，或直接发起 pull request。
