### ISSUE TITLE
语法+错别字

### ISSUE THREAD

**Issue by xxx73645** [doocs/jvm#9]
https://github.com/doocs/jvm/blob/master/docs/08-load-class-time.md
newarray 创建基本类型数组 
anewarray 创建引用类型数组

https://github.com/doocs/jvm/blob/master/docs/09-load-class-process.md
从网络中获取，如 “Applect   ”-->  Applet  ？   
通过动态代理“计数”生成代理类的二进制字节流     -->  技术？
但这两个阶段的开始“实践”仍然保持着固定的先后顺序。    -->  时间？

**Comment by yanglbme** [comment]
@xxx73645 谢谢反馈，已修改。如果发现其他问题，也欢迎直接发起 Pull Request 做出变更。
